spring:
  application:
    name: Tasks
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@//localhost:1521/XEPDB1
    username: TaskDB
    password: TaskDB123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true